# Generated by Django 6.0 on 2025-12-18 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_code', models.CharField(max_length=20, unique=True)),
                ('hotel_name', models.CharField(blank=True, max_length=300, null=True)),
                ('address', models.CharField(blank=True, max_length=600, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('state_province', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('property_url', models.URLField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_domain', models.CharField(default='ihg.com', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('nights_scraped', models.IntegerField(blank=True, null=True)),
                ('adults', models.IntegerField(blank=True, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_categories', to='parser_app.hotel')),
            ],
            options={
                'unique_together': {('hotel', 'category_code')},
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('sort_order', models.IntegerField(default=0)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='parser_app.hotel')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('hotel', 'url')},
            },
        ),
        migrations.CreateModel(
            name='RoomRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stay_date', models.DateField(blank=True, null=True)),
                ('cash_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('starting_rate_points', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='parser_app.roomcategory')),
            ],
            options={
                'indexes': [models.Index(fields=['stay_date'], name='parser_app__stay_da_25a0df_idx')],
                'unique_together': {('room_category', 'stay_date')},
            },
        ),
    ]
